In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import tensorflow as tf


In [3]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.metrics import classification_report, confusion_matrix 


# Carregando os dados de entrada a partir do arquivo .csv

In [15]:
inputs = pd.read_csv("/content/sample_data/X_In.csv")
inputs.head()





G         F         E         D         C         B         A
0  4.231242  0.780309  4.730696  2.156199  0.645430  3.787909  2.969870
1  0.636853  2.024109  2.090387  2.159703  3.502169  2.557124  3.135354
2  2.986594  0.456140  0.779718  3.521068  2.736177  3.317250  2.819513
3  0.038345  4.963844  3.928005  2.248092  3.118439  2.997237  4.477473
4  0.161174  0.377934  0.603821  0.664421  3.294831  4.219109  0.200306

# Carregando os dados de saídas esperadas a partir do arquivo .csv


In [16]:
outputs = pd.read_csv("/content/sample_data/Y_Out.csv")
outputs.head()

D8  D4  D2  D1
0   0   0   1   0
1   0   0   0   0
2   1   0   0   1
3   0   0   0   0
4   0   0   0   1

#Aqui é feita a classificação de 20% da entrada como arquivo de teste e separando os arquivos.

In [18]:
input_train, input_test, output_train, output_test = train_test_split(inputs,outputs,test_size=0.2, random_state=36)

input_train.head()

G         F         E         D         C         B         A
1744  0.634871  0.260274  0.120369  0.213064  3.333546  2.240588  2.408543
2847  2.958249  0.404613  0.064944  4.754254  4.757221  2.512015  4.034577
2867  4.996156  0.426495  0.056511  4.424242  3.204069  2.337421  4.998118
1396  3.033935  2.065023  0.213739  0.216075  3.921903  2.030379  0.030073
1111  3.132424  3.741727  0.728984  0.339927  4.283104  4.537961  0.304483

#Definindo a estrutura da rede neural. Isso inclui o número de camadas e o número de neurônios em cada camada. Como também a escolha das funções de ativação.



In [19]:
model = tf.keras.Sequential()

# Adicione uma camada de entrada com 7 neurônios, uma camada escondida com 14 neurônios
# e uma camada de saída com 4 neurônios
model.add(tf.keras.layers.InputLayer(input_shape=(7,)))
model.add(tf.keras.layers.Dense(7, activation="tanh"))
model.add(tf.keras.layers.Dense(15, activation="tanh"))
model.add(tf.keras.layers.Dense(4, activation="sigmoid"))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 7)                 56        
                                                                 
 dense_5 (Dense)             (None, 15)                120       
                                                                 
 dense_6 (Dense)             (None, 4)                 64        
                                                                 
Total params: 240
Trainable params: 240
Non-trainable params: 0
_________________________________________________________________


#Compilando o modelo especificando o otimizador e a função de perda a serem usados.

In [20]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=['binary_accuracy'])

#Treinando o modelo usando o método fit e fornecendo o conjunto de dados de treinamento e as configurações de treinamento.


In [21]:
model.fit(input_train, output_train, epochs=200, batch_size=15)

Epoch 1/200
160/160 [==============================] - 1s 2ms/step - loss: 0.6320 - binary_accuracy: 0.6469
Epoch 2/200
160/160 [==============================] - 0s 2ms/step - loss: 0.5306 - binary_accuracy: 0.7688
Epoch 3/200
160/160 [==============================] - 0s 2ms/step - loss: 0.4524 - binary_accuracy: 0.7880
Epoch 4/200
160/160 [==============================] - 0s 2ms/step - loss: 0.3838 - binary_accuracy: 0.8507
Epoch 5/200
160/160 [==============================] - 0s 2ms/step - loss: 0.3208 - binary_accuracy: 0.8885
Epoch 6/200
160/160 [==============================] - 0s 2ms/step - loss: 0.2690 - binary_accuracy: 0.8983
Epoch 7/200
160/160 [==============================] - 0s 2ms/step - loss: 0.2311 - binary_accuracy: 0.9161
Epoch 8/200
160/160 [==============================] - 0s 2ms/step - loss: 0.2038 - binary_accuracy: 0.9211
Epoch 9/200
160/160 [==============================] - 0s 2ms/step - loss: 0.1841 - binary_accuracy: 0.9229
Epoch 10/200
160/160 [======

#Fazendo uma comparação entre os valores previstos e valores esperados.

In [22]:
output_pred = model.predict(input_test)

passed = 0
failed = 0

output_test = output_test.to_numpy()

print(type(output_pred))

print(type(output_test))

for i in range(len(input_test)):
  if(np.array_equal(np.round(output_pred[i]).astype(int),output_test[i])):
    print(np.round(output_pred[i]).astype(int),"==========", output_test[i],'PASSED')
    passed+=1
  else:
    print(np.round(output_pred[i]).astype(int),"==========", output_test[i],'FAILED')
    failed+=1

print("Passed:", passed)
print("Failed:", failed)





19/19 [==============================] - 0s 1ms/step
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0 0 1 0] ========== [0 0 1 0] PASSED
[0 0 1 0] ========== [0 0 1 0] PASSED
[1 0 0 0] ========== [1 0 0 0] PASSED
[1 0 0 1] ========== [0 0 1 1] FAILED
[0 0 0 0] ========== [0 0 0 0] PASSED
[0 1 0 1] ========== [0 1 0 1] PASSED
[1 0 0 1] ========== [1 0 0 1] PASSED
[0 0 1 0] ========== [0 0 1 0] PASSED
[0 0 0 0] ========== [0 0 0 0] PASSED
[0 1 0 0] ========== [0 1 0 0] PASSED
[0 0 1 0] ========== [0 0 1 0] PASSED
[1 0 0 1] ========== [0 0 1 1] FAILED
[0 1 1 1] ========== [0 1 1 1] PASSED
[0 1 1 0] ========== [0 1 1 0] PASSED
[0 1 0 0] ========== [0 1 0 0] PASSED
[1 0 0 0] ========== [1 0 0 0] PASSED
[0 1 0 1] ========== [0 1 0 1] PASSED
[1 0 0 1] ========== [0 0 1 1] FAILED
[0 0 1 0] ========== [0 0 1 0] PASSED
[0 1 1 0] ========== [0 1 1 0] PASSED
[0 0 1 0] ========== [0 0 1 0] PASSED
[0 1 1 0] ========== [0 1 1 0] PASSED
[0 1 0 0] ========== [0 1 0 0] PASSED
[0 1 0 1] ========== [0 1

Obtenha as entradas que você deseja testar do DataFrame. 


In [12]:
loss, accuracy = model.evaluate(inputs, outputs)

print(f"Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

94/94 [==============================] - 0s 2ms/step - loss: 0.0694 - binary_accuracy: 0.9530
Loss: 0.0694
Accuracy: 0.9530


#Imprimindo os pesos do modelo:


In [23]:
for layer in model.layers:
    print(layer.trainable_weights)

[<tf.Variable 'dense_4/kernel:0' shape=(7, 7) dtype=float32, numpy=
array([[ 2.085563  , -1.457305  , -0.47749022,  0.07112011,  2.6195986 ,
        -0.08992816, -1.0736884 ],
       [ 0.03106571, -0.92151296,  2.7161283 , -0.3232227 ,  0.37116265,
         0.21104276, -1.1933911 ],
       [-0.1401347 ,  0.12878162, -0.08862717, -0.18583637, -0.02634133,
        -1.6406177 ,  0.89948255],
       [ 0.17748581, -0.26914734, -0.3149981 , -0.23732954,  2.264641  ,
         0.00416575,  1.6869562 ],
       [-0.20765749,  0.17826805,  0.2366268 ,  0.05282929,  0.7328943 ,
         0.25630677,  0.37526137],
       [-0.16400084,  0.31946626, -0.10722262,  1.8190126 ,  0.42912456,
         0.1223315 , -0.02261874],
       [-0.5527935 , -1.449402  , -0.66954046,  0.03394461,  0.44883013,
        -0.08508083,  1.8172673 ]], dtype=float32)>, <tf.Variable 'dense_4/bias:0' shape=(7,) dtype=float32, numpy=
array([ 0.08346513,  1.133553  ,  0.7020627 , -0.6469765 ,  0.19024053,
        1.2407204 ,  0.

In [11]:
model.save('model.h5')

In [14]:
# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)